JC = javac
JVM = java
MAIN = main
SOURCES = Grafo.java GrafoPondMatrizAdj.java GrafoMatrizAdj.java GrafoListaAdj.java $(MAIN).java

all:
	$(JC) $(SOURCES)



run: all
	$(JVM) $(MAIN)

clean:
	rm -f *.class